### ISSUE TITLE
uninitialized constant ProMotion::IAP (NameError) using local path for gem

### ISSUE THREAD

**Issue by dam13n** [clearsightstudio/ProMotion-iap#16]
uninitialized constant ProMotion::IAP (NameError)

Getting this error when using a local copy of the gem. Noticed the same issue had popped up in other PM add-ons due to `detect_dependencies` issues.

**Comment by jamonholmgren** [comment]
I've unfortunately never been able to get around this reliably. :-( Spent 5 hours on it once (I'm not kidding). If you figure something out, I'd be happy to hear it!

**Comment by dam13n** [comment]
Removing the PM namespace fixed it for me:
https://github.com/dam13n/ProMotion-iap/commit/dee7a5d7c28772c035d8dc2775d7bda48aab48a6

**Comment by jamonholmgren** [comment]
Good to know! And now I feel dumb about spending so much time on it.

**Comment by dam13n** [comment]
Haha, I spent a lottttt of time... Hopefully the underlying local vs. github repo issue gets figured out. : )

**Comment by jamonholmgren** [comment]
I feel pretty foolish, @dam13n ... I forgot about #8 , which I think fixes this issue.

**Comment by dam13n** [comment]
I had tried that fix. I'll give it another shot.

**Comment by jamonholmgren** [comment]
Hm, okay!

**Comment by dam13n** [comment]
Doesn't work, at least for me.
