### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by pixlwave** [clearsightstudio/ProMotion-iap#4]
Calling this twice (e.g. on viewDidLoad and user dismisses the view then reloads it):

```
product = PM::IAP::Product.new("productid")
product.retrieve do |product, error|
  # stuff
end
```

Then call this:

```
product.purchase do |status, transaction|
  # stuff
end
```

The result is this rather cryptic error (and crash):

```
Service exited due to signal: Segmentation fault: 11
Feb 13 17:49:46 macbook.local SpringBoard[10156]: Application 'UIKitApplication:com.company.App[0x7c01]' crashed.
```

(I realise I can't test this IAP process properly directly from OS X, but with only a single call to the first part, the simulator gracefully returns an error to the block).

**Comment by pixlwave** [comment]
A bit of tinkering, and it seems the problem lies in calling `product = PM::IAP::Product.new("productid")` multiple times. As a workaround, I've simply set `PRODUCT = PM::IAP::Product.new("productid")` as a constant in one of my model classes and now it no longer crashes if I load and dismiss the view multiple times.

**Comment by jamonholmgren** [comment]
Thanks for reporting this, @digitalfx , hopefully we can get that fixed soon. You're an early adopter. :)

**Comment by pixlwave** [comment]
No worries. I've had a project sat dorment waiting for me to figure out and easy way to make iaps, so you've come along and resurrected it for me :)

**Comment by jamonholmgren** [comment]
:)

Maybe try `master` now?

**Comment by pixlwave** [comment]
I'm still getting a crash if I put `product = PM::IAP::Product.new("com.company.app.purchase")` in viewDidLoad, present and dismiss the view a few times and then call `product.purchase ...` from that view. I added master with the following:
`gem 'ProMotion-iap', :git => 'https://github.com/clearsightstudio/ProMotion-iap.git', :branch => 'master'`

**Comment by jamonholmgren** [comment]
Same segmentation fault?

**Comment by pixlwave** [comment]
Yes unfortunately it is.
